name: physio_metric
description: "A Flutter application for physical therapy posture analysis and assessment."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter_riverpod: ^3.0.0-dev.15
  google_mlkit_pose_detection: ^0.14.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.0-dev.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
